//  Execute the Normal Distribution generated by direct sampling

#include "stdafx.h"
#include <iostream>
#include <fstream>
#include <iomanip>
#include <string>
#include "NormDist.h"

using namespace std;

/*****************************************************************************/
int ExecuteNormDist()
/*****************************************************************************/
{
   ofstream ofLst;
   int ret=0;
   CNormDist nd;
   double z1,z2;
   string sListFile("D:\\CompPhys\\NormDist.dat");  // file to test data
   ofLst.open(sListFile,ios::out);
   if (!ofLst) {
      cout << "Can't open file: " << sListFile << endl;
      return 1;
   }
   ofLst << fixed << setprecision(5);
   for (register int i=0; i<=100000; ++i) {
      nd.sample(z1,z2);
      ofLst << setw(12) << z1
            << setw(12) << z2 << endl;  // store data for histogram check
   }
   ofLst.close();

   return ret;
}
