//  Probkems.h

int ExecuteKepler(void);
int ExecuteDoublePend(void);
int ExecuteStatHeatEq(void);
int ExecuteMolDyn(void);
int ExecuteStatSchrodEq(void);
int ExecutePoissonEq(void);
int ExecuteTdHeatEq(void);
int ExecuteTdWaveEq(void);
int ExecuteTdSchrodEq(void);
int ExecuteSteepDesc(void);
int ExecuteConjGrad(void);
int ExecuteLCGenerator(void);
int ExecuteInversTransSamp(void);
int ExecuteRejectSamp(void);
int ExecuteIsing(void);
int ExecuteWienerProc(void);
int ExecutePoissonProc(void);
int ExecuteRandWalk(void);
int ExecuteOrnUhl(void);
int ExecuteLevy(void);
int ExecuteFractLevy(void);
int ExecuteFractRandWalk(void);
int ExecutePottsModel(void);
int ExecuteTravSalesMan(void);
int ExecuteGenetAlgTSP(void);
int ExecuteNormDist(void);
